- name: play level variables
  hosts: local
  connection: local # Ansible is connecting to localhost
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    Trainer: Bhaskar Sathi
  tasks:
  - name: print the course info #verify task-vars override play-vars
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course Name: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}"