[frontend]
172.31.23.42

[catalogue]
172.31.23.42

[local]
localhost

[local:vars]

[all:vars]
# Add this to tell Ansible which Python to use ON THE RHEL 9 HOST
ansible_python_interpreter=/usr/bin/python3

[ec2_hosts]
172.31.23.115 ansible_user=ec2-user
NAME=from inventory
COURSE=Ansible
DURATION=10Hrs
TRAINER=Bhaskar